# Generated by Django 4.1.7 on 2023-05-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_cart_subtotal_cart_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
